### ISSUE TITLE
Page Loader

### ISSUE THREAD

**Issue by gffuma** [onlinebooking/booking-frontend#21]
Trovare una soluzione per lo spinner della pagina...

**Comment by gffuma** [comment]
NB Il componente Spinner è utilizzato da altre parti in modi diversi, creare il componente Es:. HugeSpinner o HugeLoader o PageHugeLoader

**Comment by bianchimro** [comment]
sistemare fullpage in pagine dove serve
aggiungere testo prenotazioni
